# Autogenerated Makefile -*- makefile -*-
# Copyright (C) 2009-2010 Ross Biro.
# Do not edit. Do not Distribute.
#
-include make_parts/begin/*.inc

-include make/textus/template/Template.inc

-include make_parts/middle/*.inc


-include make_parts/end/*.inc

runtests: runtests_textus_template_Template

valgrind: valgrind_textus_template_Template

