# Autogenerated Makefile -*- makefile -*-
# Copyright (C) 2009-2010 Ross Biro.
# Do not edit. Do not Distribute.
#
-include make_parts/begin/*.inc

-include make/textus/base/init/Init.inc

-include make_parts/middle/*.inc


-include make_parts/end/*.inc

runtests: runtests_textus_base_init_Init

valgrind: valgrind_textus_base_init_Init

