# Autogenerated Makefile -*- makefile -*-
# Copyright (C) 2009-2010 Ross Biro.
# Do not edit. Do not Distribute.
#
-include make_parts/begin/*.inc

-include make/textus/network/ssl/SSL.inc

-include make_parts/middle/*.inc


-include make_parts/end/*.inc

runtests: runtests_textus_network_ssl_SSL

valgrind: valgrind_textus_network_ssl_SSL

