# Autogenerated Makefile -*- makefile -*-
# Copyright (C) 2009-2010 Ross Biro.
# Do not edit. Do not Distribute.
#
-include make_parts/begin/*.inc

-include make/textus/config/Config.inc

-include make_parts/middle/*.inc


-include make_parts/end/*.inc

runtests: runtests_textus_config_Config

valgrind: valgrind_textus_config_Config

