# Autogenerated Makefile -*- makefile -*-
# Copyright (C) 2009-2010 Ross Biro.
# Do not edit. Do not Distribute.
#
-include make_parts/begin/*.inc

-include make/textus/random/Random.inc

-include make_parts/middle/*.inc


-include make_parts/end/*.inc

runtests: runtests_textus_random_Random

valgrind: valgrind_textus_random_Random

