#!/bin/bash
# Copyright (c) 2011 Ross Biro -*- sh -*-
#
# Build everything and run the unittests.
#
#
#   This program is free software: you can redistribute it and/or
#   modify it under the terms of the GNU General Public License as
#   published by the Free Software Foundation, version 3 of the
#   License.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#   General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see
#   <http://www.gnu.org/licenses/>.
#
#
CKSUM=$( md5sum $0 )

PATH=$HOME/bin:$PATH
while [ "$CKSUM" == "$( md5sum $0 )" ]; do
    do_tests
done
exec continuous_build
