#!/bin/bash
# Copyright (c) 2009 Ross Biro -*- sh -*-
#
# Run all the unittests
# return 0 on success 1 on failure.
#

#
#   This program is free software: you can redistribute it and/or
#   modify it under the terms of the GNU General Public License as
#   published by the Free Software Foundation, version 3 of the
#   License.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#   General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see
#   <http://www.gnu.org/licenses/>.
#
#

if [ "$1" = "" ]; then
   DIR="$(pwd)"
else
   DIR="$1"
   shift
fi

cd "$DIR"

make runtests
if [ $? != 0 ]; then
    exit 1;
fi

exit 0

