# Autogenerated Makefile -*- makefile -*-
# Copyright (C) 2009-2010 Ross Biro.
# Do not edit. Do not Distribute.
#
-include make_parts/begin/*.inc

-include make/textus/file/File.inc

-include make_parts/middle/*.inc


-include make_parts/end/*.inc

runtests: runtests_textus_file_File

valgrind: valgrind_textus_file_File

